// src/components/Battle/CommandPanel/Structure.svelte
<script>
  export let hull = {};
  export let armor = {};

  import Hull from './Hull.svelte';
  import Armor from './Armor.svelte';
</script>

<style>
div {
  background-color: red;
}
</style>

<fielset class="structure">
  <legend>Structure</legend>
  <Hull {...hull} />
  <Armor {...armor} />
</fielset>

// src/components/Battle/CommandPanel/Structure/index.jsx
import React from 'react';

import Hull from './Hull';
import Armor from './Armor';
import Shields from './Shields';

export default function Structure({ hull, armor, shields }) {
  console.log(shields);

  return (
    <div>
      <fieldset className="structure">
        <legend>Structure</legend>
        <Hull {...hull} />
        <Armor {...armor} />
        <Shields shields={shields} />
      </fieldset>
    </div>
  );
}
