// src/components/Battle/CommandPanel/Navigation/index.svelte
<script>
  import fp from 'lodash/fp';

  import Drive from './Drive/index.svelte';
  import NavItem from './NavItem.svelte';

  export let drive;
  export let navigation;
  export let orders = {};

  let thrust_used;
  $: thrust_used = fp.getOr(0, 'course.thrust_used', navigation);

  const maneuver_types = ['thrust', 'turn', 'bank'];

  const get_min = type => fp.getOr(0,[
    'maneuvers', type, 0
  ]);
  const get_max = type => fp.getOr(0,[
    'maneuvers', type, 1
  ]);

</script>

<fieldset>
  <legend>Navigation</legend>

  <Drive {drive} {thrust_used} />

  {#each maneuver_types as type (type)}
    <NavItem
      min={get_min(type)(navigation)}
      max={get_max(type)(navigation)}
      value={orders[type]||0}
      label={type}
      on:change={x => console.log(x.target.value)}/>
  {/each}

</fieldset>

// src/components/Battle/CommandPanel/Navigation/index.jsx
import React from 'react';
import fp from 'lodash/fp';

import Drive from './Drive';
import NavItem from './NavItem';

export default function Navigation({
  drive,
  orders,
  navigation,
  onOrdersChange = () => {},
}) {
  return (
    <fieldset>
      <legend>Navigation</legend>

      <Drive
        drive={drive}
        thrust_used={fp.getOr(0, 'navigation.course.thrust_used', this)}
      />

      {['thrust', 'turn', 'bank']
        .map(type => [type, navigation.maneuvers[type]])
        .filter(x => x[1])
        .map(([type, maneuvers]) => (
          <NavItem
            key={type}
            min={maneuvers[0]}
            max={maneuvers[1]}
            value={orders[type]}
            label={type}
            onChange={value => onOrdersChange({[type]: value})}
          />
        ))}
    </fieldset>
  );
}
