// src/components/Battle/CommandPanel/Navigation/NavItem.jsx
import React from 'react';

export default function NavItem({
  min,
  max,
  label,
  value,
  onChange = () => {}
}) {
  return (
    <div>
      <label>{label}</label>
      <input
        type="range"
        min={min}
        max={max}
        value={value}
        onChange={e => onChange(e.target.value)}
      />
    </div>
  );
}

// src/components/Battle/CommandPanel/Navigation/NavItem.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();

  export let min;
  export let max;
  export let label;
  export let value;

</script>

<div>
  <label>{label}</label>
  <input type="range" {min} {max} {value} on:change />

</div>

  <style>
  div {
    display: flex;
    align-content: baseline;
  }
    label {
      display: inline-block;
      width: 5em;
    }
  </style>
