// src/components/Battle/CommandPanel/Navigation/NavItem.jsx
import React from 'react';

export default function NavItem({
  min,
  max,
  label,
  value,
  onChange = () => {}
}) {
  return (
    <div>
      <label>{label}</label>
      <input
        type="range"
        min={min}
        max={max}
        value={value}
        onChange={e => onChange(e.target.value)}
      />
    </div>
  );
}

// src/components/Battle/CommandPanel/Navigation/NavItem.vue
<template>
  <v-slider
    :label="label"
    :min="min"
    :max="max"
    :value="value"
    @change="change"
  />
</template>

<script>
export default {
  props: {
    label: { required: true },
    min: { required: true },
    max: { required: true },
    value: { required: true }
  },
  components: {},
  computed: {},
  filters: {},
  methods: {
    change(value) {
      this.$emit("change", {
        [this.label]: value
      });
    }
  }
};
</script>

<style scoped></style>
