// src/components/Battle/CommandPanel/Firecons/index.jsx
import React from 'react';
import Firecon from "./Firecon";


export default function Firecons({ bogey_id, firecons, weapons, targets = [] }) {
const weapons_for = (id) => weapons.filter(({ firecon_id }) => firecon_id === id);

    return <fieldset>
        <legend>firecons</legend>

        { firecons.map( f => <Firecon key={f.id}
            firecon_id={f.id}
            weapons={weapons_for(f.id)}
            targets={targets}
            target_id={f.target_id} />
        )
        }

        <Firecon weapons={weapons_for(undefined)} />

    </fieldset>
}

/*
<template>
  <fieldset>

    <Firecon
      :bogey_id="bogey_id"
      v-for="firecon in firecons"
      :firecon_id="firecon.id"
      :key="firecon.id"
      :weapons="weapons_for(firecon.id)"
      :targets="targets"
      :target_id="firecon.target_id"
    />

    <Firecon :bogey_id="bogey_id" :weapons="weapons_for()" />
  </fieldset>
</template>


*/

// src/components/Battle/CommandPanel/Firecons/index.vue
<template>
  <fieldset>
    <legend>firecons</legend>

    <Firecon
      :bogey_id="bogey_id"
      v-for="firecon in firecons"
      :firecon_id="firecon.id"
      :key="firecon.id"
      :weapons="weapons_for(firecon.id)"
      :targets="targets"
      :target_id="firecon.target_id"
    />

    <Firecon :bogey_id="bogey_id" :weapons="weapons_for()" />
  </fieldset>
</template>

<script>
import Firecon from "./Firecon";

/**
 * @example ./firecons.md
 */
export default {
  name: "Firecons",
  components: { Firecon },
  props: {
    bogey_id: { required: true },
    firecons: { default: () => [] },
    weapons: { default: () => [] },
    targets: { default: () => [] }
  },
  computed: {},
  filters: {},
  methods: {
    weapons_for(id) {
      return this.weapons.filter(({ firecon_id }) => firecon_id === id);
    }
  }
};
</script>

<style scoped></style>
