// src/components/Battle/CommandPanel/index.jsx
import React from 'react';
import Structure from "./Structure";
import fp from 'lodash/fp';

const Todo = () => <div>Todo</div>;

export default function CommandPanel({bogey}) {

    const orders_sent = fp.getOr(false,'orders.issued',bogey);
    const send_orders = () => { console.log("sending orders") };

    return <div>
    <h1>{ bogey.name || bogey.id }</h1>

        <Structure {...bogey.structure} />

        <input type="button"
            value={ orders_sent ? "orders sent" : "send orders" }
                disabled={ orders_sent}
            onClick={send_orders}
        />

        </div>;
}
/*
<template>

    <Navigation
      :drive="bogey.drive"
      :orders="order_nav"
      :navigation="bogey.navigation"
        @orders_change="orders_change"
    />

    <Firecons :bogey_id="bogey.id" v-bind="weaponry" />
  </div>
</template>

<script>
import Firecons from "./Firecons";
import Navigation from "./Navigation";

import fp from "lodash/fp";
import { useBattle } from '../../../hooks/battle';

export default {
  name: "CommandPanel",
  props: {
    bogey: { required: true },
    bogeys: { default: () => [] }
  },
  components: { Firecons, Navigation, Structure },
  computed: {
    order_nav() {
      return fp.getOr({}, "bogey.orders.navigation", this);
    },
    weaponry() {
      return this.bogey.weaponry;
    },
    orders_sent() {
      return fp.get("bogey.orders.issued")(this);
    },
    order_button_label() {
      return this.orders_sent ? "orders sent" : "send orders";
    }
  },
  filters: {},
  methods: {
    send_orders() {
      this.$emit("send_orders", this.bogey.id, fp.get("bogey.orders", this));
    }
  },
    setup({bogey}) {
        const { add_bogey_orders } = useBattle();

        console.log("???", bogey);

        return {
            orders_change(change) {
                console.log(change);
                add_bogey_orders(bogey.id,{ navigation: change });
            }
        }
    }
};
</script>

<style scoped></style>
*/

// src/components/Battle/CommandPanel/index.svelte
<script>
  export let bogey = {};

  import fp from 'lodash/fp';
  import Structure from './Structure.svelte';
  import Navigation from './Navigation/index.svelte';
  import Shields from './Shields.svelte';

  let orders_sent;
  $: orders_sent = fp.getOr(false, 'orders.issued', bogey);

  const send_orders = () => {};

  let navigation_orders;
  $: navigation_orders = fp.getOr( {}, 'orders.navigation', bogey );

</script>

<div>
  <h1>{bogey.name}</h1>

  <Structure {...bogey.structure} />

      <input
        type="button"
        value={orders_sent ? 'orders sent' : 'send orders'}
        disabled={orders_sent}
        on:click={send_orders}
      />

      <Navigation
        drive={bogey.drive}
        orders={navigation_orders}
        navigation={bogey.navigation}
      />

      <Shields shields={fp.getOr([],'weaponry.shields',bogey)} />

</div>
