// src/components/Battle/CommandPanel/Navigation/Drive.vue
<template>
  <div class="drive">
    drive: {{ thrust_used }} / {{ current }}
    <div class="bar">
      <v-progress-linear :value="(100 * thrust_used) / current" color="blue" />
    </div>
  </div>
</template>

<script>
export default {
  props: {
    current: { required: true },
    thrust_used: { default: 0, type: Number }
  },
  components: {},
  computed: {},
  filters: {}
};
</script>

<style scoped>
.bar {
  width: 10em;
  display: inline-block;
}
</style>

// src/components/Battle/CommandPanel/Navigation/Drive/index.svelte
<script>
  export let current = 0;
  export let rating = 0;
  export let thrust_used = 0;
</script>


    <div class="drive">
      drive
      <span>{current}</span>
        <progress max={current} value={thrust_used}>
          {thrust_used}
        </progress>

    </div>

  <style>
    .drive {
      display: flex;
    }
    span {
      flex: 1;
      display: inline-block;
      text-align: right;
      font-family: var(--font-accent);
      margin-right: 1em;
    }
    progress {
      width: 170px;
    }
  </style>
